services:
  base:
    build: .
    volumes:
      - .:/dotfiles

  ci:
    extends:
      service: base
    init: true
    volumes:
      - ./.ci-cache/nvim:/root/.local/share/nvim
    command: >
      bash -c "
        ansible-playbook -i localhost, -c local playbook.yml -e dotfiles_home=/root -e dotfiles_repo_root=/dotfiles ${DOTFILES_ANSIBLE_EXTRA_ARGS:-} &&
        source ~/.bash_profile &&
        DOTFILES=/dotfiles goss validate --format tap &&
        ./tests/test_helper/bats-core/bin/bats tests/integration/
      "

  dev:
    extends:
      service: base
    stdin_open: true
    tty: true
    command: >
      bash -c "
        ansible-playbook -i localhost, -c local playbook.yml -e dotfiles_home=/root -e dotfiles_repo_root=/dotfiles && bash
      "
