services:
  base:
    build: .
    environment:
      GIT_CONFIG_PARAMETERS: "'safe.directory=*'"
    volumes:
      - .:/dotfiles

  ci:
    extends:
      service: base
    init: true
    environment:
      DOTFILES_ANSIBLE_EXTRA_ARGS: ${DOTFILES_ANSIBLE_EXTRA_ARGS---skip-tags brew,rust}
    volumes:
      - ./.ci-cache/nvim:/root/.local/share/nvim
      - ./.ci-cache/mise:/root/.local/share/mise
      - ./.ci-cache/mise-cache:/root/.cache/mise
      - ./.ci-cache/tmux:/root/.tmux/plugins
      - ./.ci-cache/go:/root/dev/go
      - ./.ci-cache/coc:/root/.config/coc
    command: >
      bash -c "
        set -o pipefail &&
        ./bootstrap.sh $${DOTFILES_ANSIBLE_EXTRA_ARGS:-} | tee /tmp/first-converge.log &&
        ./bootstrap.sh $${DOTFILES_ANSIBLE_EXTRA_ARGS:-} | tee /tmp/second-converge.log &&
        ! grep -Eq 'changed=[1-9][0-9]*' /tmp/second-converge.log &&
        source ~/.bash_profile &&
        DOTFILES=/dotfiles goss validate --format tap &&
        ./tests/test_helper/bats-core/bin/bats tests/integration/
      "

  dev:
    extends:
      service: base
    stdin_open: true
    tty: true
    command: >
      bash -c "
        ./bootstrap.sh $${DOTFILES_ANSIBLE_EXTRA_ARGS:-} && bash
      "
