[tools]
node = "lts"
ruby = "4"
go = "latest"
bun = "latest"
tombi = "latest"

[settings]
legacy_version_file = true
ruby.compile = false

[shell_alias]
coi = "co $INTEGRATION_BRANCH"
mi = "merge $INTEGRATION_BRANCH"
fa = "fem; fed; fei"
fei = "f origin $INTEGRATION_BRANCH:$INTEGRATION_BRANCH"
