---
- name: Detect npm
  ansible.builtin.command: "command -v npm"
  register: npm_bin
  changed_when: false
  failed_when: false

- name: Install global npm modules
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: "{{ 'latest' if dotfiles_state == 'latest' else 'present' }}"
  loop: "{{ dotfiles_npm_globals }}"
  when: npm_bin.rc == 0
