name: ubuntu-dotfiles-tests

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run bash function tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run bash function tests
        run: just test-unit

      - name: Run Docker environment tests
        run: just test
